import { Rubik } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

export const metadata = {
  title: "Maon Test",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable} antialiased`}
      >
        <header className="flex justify-center px-12 py-5 md:py-6 border-b border-[#272735] md:border-b-0">
          <Logo/>
        </header>
        {children}
      </body>
    </html>
  );
}

const Logo = () => {
  return (
    <Image 
      src={'/blott-logo.svg'} 
      alt={'Blott Logo'} 
      title={'Blott Logo'} 
      height={48} 
      width={200}
      className="size-full max-w-[121px] md:max-w-[200px] aspect-[200/48]"
    />
  )
}